### PR TITLE
changed jQuery .find expression to work with new twitter UI

### PR DESCRIPTION
**Pull request by Kroissan**
Address #18

### CODE REVIEW

**Comment by biast12** [comment]
@Flkalas pls accept

**Comment by ahmed2m** [comment]
Can you use the fork and publish it as a separate extension? the developer seems inactive

**Comment by biast12** [comment]
yeah i have tried to contact him on other platforms too but nothing seems to work

**Comment by Kroissan** [comment]
I don't really know how to publish on chrome web store or mozilla. What you can do is download the latest zip here: https://github.com/Kroissan/TwitterMediaAssist/releases
Then follow this tutorial https://webkul.com/blog/how-to-install-the-unpacked-extension-in-chrome/
You can select the 'src' folder to load the extension manually

**Comment by biast12** [comment]
Bruh i just noticed he updated the firefox version to 3.0.6 (we're on 3.0.5 on chrome) 4 days before your commit https://addons.mozilla.org/en-US/firefox/addon/twitter-media-assist-ff/

@Flkalas pls both accept this PR and release the update on chrome too

**Comment by biast12** [comment]
THANKS!

**Pull request merged**
